@ISP_PROJEKTAS.Server_HostAddress = http://localhost:5031

GET {{ISP_PROJEKTAS.Server_HostAddress}}/api/patiekalas/1
Accept: application/json
###
GET {{ISP_PROJEKTAS.Server_HostAddress}}/api/restoranas/2
Accept: application/json
