@ISP_PROJEKTAS.Server_HostAddress = http://localhost:5031

GET {{ISP_PROJEKTAS.Server_HostAddress}}/api/patiekalas
Accept: application/json
###
GET {{ISP_PROJEKTAS.Server_HostAddress}}/api/restoranas/2
Accept: application/json
###
GET {{ISP_PROJEKTAS.Server_HostAddress}}/api/patiekalas/ingredientai/9
Accept: application/json
###
GET {{ISP_PROJEKTAS.Server_HostAddress}}/KrepselioPreke
Accept: application/json